modLoader="javafml"
loaderVersion="[4,)"
license="Apache-2.0 license http://www.apache.org/licenses/LICENSE-2.0"

[[mods]]
modId="bedrockitetools"
version="1.5.0-alpha"
displayName="Bedrockite Tools"
displayURL="https://github.com/Miki85cz/BedrockiteToolsMod"
authors="§a§lMiki85cz"

description='''
§rThis mod is an addon for §bBedrockite §r that makes all the tools upgradeable to Bedrockite

§6If you find any issue please report it! https://github.com/Miki85cz/BedrockiteToolsMod/issues
'''

logoFile="bedrockitetools.png"

[[mixins]]
config="bedrockitetools.mixins.json"

[[dependencies.bedrockitetools]]
    modId="neoforge"
    type="required"
    versionRange="[21.0.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.bedrockitetools]]
    modId="minecraft"
    type="required"
    versionRange="[1.21, 1.21.2)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.bedrockitetools]]
    modId="bedrockite"
    type="required"
    versionRange="[1.4.8-beta, 1.5.1-beta]"
    ordering="AFTER"
    side="BOTH"
    
[[dependencies.bedrockitetools]]
    modId="bedrockitearmor"
    type="optional"
    versionRange="[1.0.0,)"
    ordering="BEFORE"
    side="BOTH"